# Site settings
<<<<<<< HEAD
title: 'Alper Bassarac'
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno/'
=======
title: 'Alper Başsaraç'
description: 'LPIC'
url: 'https://alperbas.github.io/' 
baseurl: ''
>>>>>>> refs/remotes/origin/gh-pages
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
<<<<<<< HEAD
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes
=======
  name: 'Alper Başsaraç'
  email: alper.bassarac@gmail.com
  twitter_username: alper292
  github_username:  alperbas
  linkedin_username:  alperbas
>>>>>>> refs/remotes/origin/gh-pages

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
