# Site settings
title: 'Alper Başsaraç'
description: 'LPIC'
url: 'https://alperbas.github.io/' 
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Alper Başsaraç'
  email: alper.bassarac@gmail.com
  twitter_username: alper292
  github_username:  alperbas
  linkedin_username:  alperbas

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']