# Site settings
title: 'Alper Başsaraç'
description: 'LPIC-1 MSCE ITIL SUSE VCA-DCV'
url: 'https://alperbas.github.io/' 
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alper Başsaraç'
  email: alper.bassarac@gmail.com
  twitter_username: alper292
  github_username:  alperbas
  linkedin_username:  alperbas

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
