# Site specific settings
title: "Alper Title"
name: "alperbas"
keywords: "Cok guzel bir web site"
baseurl: "/darcli"
url: "https://alperbas.github.io"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
